use super::*;

// Frozen from adaptive-001-baseline/source; these are not regenerated by the codec.
const DESCRIPTORS: [&str; 3] = [
    concat!(
        "bota-drysua-checkpoint/v12;linked_schemas=action,feature,model,ppo,map2_reward;linked_hash=fnv1a_descriptor_then_ordered_version_le32_hash_le64_then_map2_reward_descriptor_utf8;files=checkpoint.safetensors,checkpoint.meta,drysua.weights.safetensors,immutable_sha256_tensor_generation;",
        "tensors=model.parameters,adam.first_moment,adam.second_moment;dtype=f32;runtime_metadata=action_feature_model_ppo_schema_hashes,ppo_schema_version,ppo_rules_audit_version,map2_reward_schema_version,map2_reward_schema_hash,map2_reward_schema_descriptor;load=exact_names_shapes_dtype_finite_schema_sha256,no_legacy_runtime_or_resume,canonical_tensor_fallback;",
        "initialization=explicit_pinned_m14_m16_m17_original_metadata_reward1_and_padding_or_m19u162_9d0b8812_original_metadata_frozen_reward3_full_SHA_finite62_tensor_Candle_append_global_rows90to92_1024_positive_zeros_or_m21u300_b29752ac_original_metadata_frozen_reward5_full_SHA_same_shape1700020_all_bits_preserved_no_critic_or_actor_rescaling_new_provenance_no_gameplay_or_reward_equivalence_fresh_optimizer_progress_mastery_rng_league,no_m18_or_m20_source_pin;",
        "manifest=git_simulator_features_map2_scope_cap27900_including900_pregame_seed_device_batch_command_rules32_progress_rng_curriculum_league;mastery_config=after_run_rules_presence_u8_then_window_u32_weak_percent_u8_teacher_percent_u8_window1to1024_percent1to100;mastery_progress=after_league_references_presence_u8_then_stage_u8_0weak1teacher2completed_stage_games_u64_count_u32_and_oldest_to_newest_bool_u8_flags_count_equals_min_stage_games_config_window,exact_config_state_pairing,active_window_not_qualified_completed_window_full_qualified;",
        "mastery_counters=stage_games_bounded_and_multiple_of_environments2or4or6_weak_games_equal_updates_times_environments_later_stages_require_prior_full_batch_rounded_window;mastery_scope=typed_config_and_canonical_run_before_tensor_read_or_mutation_Git_migration_cannot_change_config,no_fake_rng_states;observation=feature22_action5_unchanged_legal_set_global92_unit84_all_indices_preserved_tower_remaining90_opening_pending91_no_mastery_inputs;",
        "reward7=terminal_win.2_loss_neg.2_draw0_taskcap_neg.2_dense_unchanged_win_only_victory_time_bonus_continuous_native_clock_distinct_outcomes_errors_not_rewards_no_terminal_dominance;wire_rebase=bota78427bb_new_event_order_missed_ignored_cheat_never_issued_no_reward_effect_attack_time_ms_ticks_bound_collision_no_old_alias;save=immutable_generation,canonical_copy,recoverable_manifest_commit_last,file_and_directory_fsync;"
    ),
    concat!(
        "bota-drysua-checkpoint/v13;profile=annealed;",
        "linked_schemas=action,feature,model,ppo_annealed,map2_reward,base_checkpoint12;linked_hash=fnv1a_descriptor_then_ordered_version_le32_hash_le64_then_map2_reward_descriptor_utf8;",
        "base=exact_linked_checkpoint12_tensor_names_shapes_dtype_finite_SHA256_run_progress_rng_device_features_and_durable_commit_contract;",
        "manifest=unchanged_checkpoint12_field_order_and_five_encoded_linked_schemas,base_checkpoint12_identity_hash_link_only;config=unchanged64bytes_five_le32_dimensions_eleven_f32,budget_derived_from_exact_header_and_linked_PPO_profile_no_extra_tag;",
        "capacity=even_games2to40,retained1163_per_game,samples46520_max,decision_interval3,gamma_tick1,concurrent_world_limit_unchanged;progress=committed_rollout_samples_le_updates_times_configured_games_times1163_checked;mastery=forbidden;actor_learner_pipeline=forbidden;",
        "runtime=explicit_annealed_PPO_version_hash_same_other_metadata_fields_and_tensor_contract,accept_only_exact_standard_or_annealed_tuple_no_relabel;standard=checkpoint12_and_PPO37_bytes_unchanged;"
    ),
    concat!(
        "bota-drysua-checkpoint/v14;profile=wide_annealed;",
        "linked_schemas=action,feature,model,ppo_wide_annealed39,map2_reward,base_checkpoint13;linked_hash=fnv1a_descriptor_then_ordered_version_le32_hash_le64_then_map2_reward_descriptor_utf8;",
        "base=exact_linked_checkpoint13_tensor_names_shapes_dtype_finite_SHA256_run_progress_rng_device_features_and_durable_commit_contract;",
        "manifest=unchanged_checkpoint13_field_order_and_five_encoded_linked_schemas,base_checkpoint13_identity_hash_link_only;config=unchanged64bytes_five_le32_dimensions_eleven_f32,budget_derived_from_exact_header_and_linked_PPO_profile_no_extra_tag;",
        "capacity=even_games2to80,retained1163_per_game,samples93040_max,decision_interval3,gamma_tick1,concurrent_worlds1to64;progress=committed_rollout_samples_le_updates_times_configured_games_times1163_checked;mastery=forbidden;actor_learner_pipeline=forbidden;",
        "runtime=explicit_wide_annealed_PPO39_version_hash_same_other_metadata_fields_and_tensor_contract,accept_only_exact_standard_or_annealed_or_wide_annealed_tuple_no_relabel;legacy=checkpoint12_PPO37_and_checkpoint13_PPO38_bytes_unchanged;"
    ),
];

#[test]
fn fixed_descriptors_and_linked_identities_match_pre_adaptive_golden() {
    assert_eq!(
        [
            CHECKPOINT_SCHEMA_DESCRIPTOR,
            CHECKPOINT_ANNEALED_SCHEMA_DESCRIPTOR,
            CHECKPOINT_WIDE_ANNEALED_SCHEMA_DESCRIPTOR
        ],
        DESCRIPTORS
    );
    let standard = crate::model::linked_schema_hash(DESCRIPTORS[0], &LINKED_SCHEMAS);
    let annealed =
        checkpoint_profile_hash(PpoSampleBudget::Annealed, DESCRIPTORS[1], (12, standard));
    let wide = checkpoint_profile_hash(
        PpoSampleBudget::WideAnnealed,
        DESCRIPTORS[2],
        (13, annealed),
    );
    for (budget, identity) in [
        (PpoSampleBudget::Standard, (12, standard)),
        (PpoSampleBudget::Annealed, (13, annealed)),
        (PpoSampleBudget::WideAnnealed, (14, wide)),
    ] {
        assert_eq!(checkpoint_schema_identity(budget), identity);
    }
}

#[test]
fn fixed_manifest_body_matches_golden_without_presence_byte_or_adaptive_tail() {
    for budget in [
        PpoSampleBudget::Standard,
        PpoSampleBudget::Annealed,
        PpoSampleBudget::WideAnnealed,
    ] {
        let mut artifact = capacity_tests::manifest_artifact(budget, 0, 0);
        artifact.run.git_commit = "g".to_owned();
        artifact.run.simulator_commit = "s".to_owned();
        artifact.run.command_line = "train".to_owned();
        artifact.run.run_seed = 0;
        artifact.config.environments = 2;
        artifact.progress.rng_states.clear();
        artifact.shuffle = (0, 0);
        let encoded = encode_manifest(&artifact, [42; 32]).expect("fixed manifest");
        let golden = fixed_body_golden();
        assert_eq!(&encoded[80..], golden);
        let decoded = decode_manifest(&encoded).expect("old load without adaptive flag");
        assert_eq!(decoded.progress.adaptive_environment, None);
        assert_eq!(decoded.run, artifact.run);
    }
}

fn fixed_body_golden() -> Vec<u8> {
    let features = compiled_features();
    let mut golden = b"\x01\0g\x01\0s".to_vec();
    golden.extend_from_slice(&(features.len() as u16).to_le_bytes());
    golden.extend_from_slice(features.as_bytes());
    golden.extend_from_slice(b"\x05\0train");
    golden.extend_from_slice(&[0; 8]);
    golden.extend_from_slice(b"\x02\0\x02\0\0\0\0\0\0\0\x02\0\0\x20\0\0\0\0");
    // Zero counters, absent evaluation, empty RNG/league, and absent mastery.
    golden.extend_from_slice(&[0; 48]);
    golden.extend_from_slice(b"\x03\0\0\0\x8b\x04\0\0\x02\0\0\0\x01\0\0\0\0\x02\0\0");
    for value in [
        0.2f32, 0.5, 0.01, 3.0e-6, 0.9, 0.999, 1.0e-5, 0.5, 1.0, 0.98, 0.02,
    ] {
        golden.extend_from_slice(&value.to_le_bytes());
    }
    golden.extend_from_slice(&[0; 32]);
    golden.extend_from_slice(&[42; 32]);
    golden
}
