apiVersion: 1
datasources:
  - name: Prometheus
    uid: drysua-prometheus
    type: prometheus
    access: proxy
    url: $DRYSUA_PROMETHEUS_URL
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 5s
      queryTimeout: 10s
