use std::collections::VecDeque;
use std::error::Error;
use std::fmt;
use std::num::NonZeroU64;
use std::sync::atomic::{AtomicU64, Ordering};

use bota_proto::{
    AbilityId, DamageKind, EntityId, EventKind, Fixed, HeroId, MapId, MatchInfo, Pick, PlayerView,
    ShopEntry, SlotId, Team, TickMode, UnitKind, UnitView, Vec2, WorldView,
};

use crate::SHADOW_FIEND;

pub(crate) const COURIER_ITEM_SLOTS: usize = 6;
pub(crate) const HERO_ITEM_SLOTS: usize = 9;
pub(crate) const STASH_ITEM_SLOTS: usize = 6;

/// World units covered by one terrain RLE cell in the current drysua schema.
pub const TERRAIN_CELL_SIZE: i32 = 64;

/// Maximum number of seats in one match.
pub const MAX_SEATS: usize = 10;
/// Maximum number of unit tokens selected by the future feature encoder.
pub const UNIT_TOKENS: usize = 96;
/// Maximum number of entity records retained by the tracker.
pub const MAX_TRACKED_ENTITIES: usize = 256;
/// Maximum number of projectiles in one snapshot.
pub const MAX_PROJECTILES: usize = 32;
/// Maximum number of ground items in one snapshot.
pub const MAX_LOOT: usize = 16;
/// Number of fixed Shadow Fiend ability slots.
pub const SHADOW_FIEND_ABILITY_SLOTS: usize = 6;
/// Maximum number of ability slots accepted for another visible hero.
pub const MAX_ABILITY_SLOTS: usize = 8;
/// Number of own hero, stash, and courier item slots.
pub const OWN_ITEM_SLOTS: usize = HERO_ITEM_SLOTS + STASH_ITEM_SLOTS + COURIER_ITEM_SLOTS;
/// Maximum number of shop entries.
pub const MAX_SHOP_ITEMS: usize = 64;
/// Maximum number of point candidates generated by the future action builder.
pub const MAX_POINT_CANDIDATES: usize = 48;
/// Maximum number of recent events retained.
pub const MAX_RECENT_EVENTS: usize = 64;
/// Maximum events accepted per batch, equal to half the wire payload byte cap.
/// This exceeds the number of `EventKind` values encodable in a valid payload.
pub const MAX_EVENTS_PER_BATCH: usize = bota_proto::MAX_PAYLOAD_LEN / 2;
/// Maximum remembered age in game ticks.
pub const HISTORY_TICKS: u32 = 480;
/// Maximum number of global summaries retained.
pub const MAX_HISTORY_SUMMARIES: usize = HISTORY_TICKS as usize + 1;
/// Global summary ages, from oldest to current.
pub const HISTORY_AGES: [u32; 7] = [480, 240, 120, 60, 30, 15, 0];
/// Maximum number of static trees accepted from match metadata.
pub const MAX_STATIC_TREES: usize = 4_096;
/// Maximum number of planted trees in one snapshot.
pub const MAX_PLANTED_TREES: usize = 4_096;
/// Maximum number of effects accepted on one unit.
pub const MAX_EFFECTS_PER_UNIT: usize = 32;
/// Maximum terrain axis accepted from match metadata.
pub const MAX_TERRAIN_AXIS: u32 = 512;
/// Maximum number of terrain runs accepted from match metadata.
pub const MAX_TERRAIN_RUNS: usize = 262_144;
/// Maximum number of opaque terrain cells accepted from match metadata.
pub const MAX_OPAQUE_CELLS: usize = 262_144;
/// Maximum number of components accepted for one shop entry.
pub const MAX_SHOP_COMPONENTS: usize = 16;

static NEXT_TRACKER_LINEAGE: AtomicU64 = AtomicU64::new(1);

/// Public match terms used by state and feature construction.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct MatchMetadata {
    /// Selected map.
    pub map: MapId,
    /// Simulation ticks per second.
    pub tick_rate: u16,
    /// Ticks before game time zero.
    pub pregame_ticks: u32,
    /// Number of terrain cells on each map axis.
    pub terrain_cells: u32,
    /// Tick advancement mode.
    pub mode: TickMode,
    /// Number of seats in the match.
    pub seats: u8,
}

/// Exact bounded static inputs used by policy components.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct StaticTrackerProvenance {
    slot: SlotId,
    team: Team,
    metadata: MatchMetadata,
    static_trees: Vec<Vec2>,
    terrain_rle: Vec<(u16, u8)>,
    opaque_cells: Vec<(u16, u16)>,
    shop: Vec<ShopEntry>,
    roster: Vec<Pick>,
}

/// Exact bounded provenance used to pair action masks and observations.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct TrackerProvenance {
    lineage: NonZeroU64,
    revision: u64,
    static_data: StaticTrackerProvenance,
    previous_snapshot: Option<WorldView>,
    snapshot: WorldView,
    entities: Vec<EntityTrack>,
    recent_events: VecDeque<ObservedEvent>,
    snapshot_events: VecDeque<ObservedEvent>,
    summaries: VecDeque<GlobalSummary>,
    last_event_tick: Option<u32>,
    peak_allied_structures: Option<u32>,
    peak_enemy_structures: Option<u32>,
    structure_baseline_complete: bool,
}

/// Exact displacement observed between two visible snapshots.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct VelocityEstimate {
    /// Position difference without division or rounding.
    pub delta: Vec2,
    /// Positive number of game ticks covered by `delta`.
    pub elapsed_ticks: u32,
}

/// One observed damage relation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DamageObservation {
    /// Tick that produced the event.
    pub tick: u32,
    /// Health actually removed.
    pub amount: i32,
    /// Damage reduction category.
    pub kind: DamageKind,
    /// Whether the event reports a critical strike.
    pub crit: bool,
    /// Other entity in the damage relation, when one was reported.
    pub counterpart: Option<EntityId>,
}

/// One observed healing relation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HealObservation {
    /// Tick that produced the event.
    pub tick: u32,
    /// Health actually restored.
    pub amount: i32,
    /// Other entity in the healing relation, when one was reported.
    pub counterpart: Option<EntityId>,
}

/// One observed death.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DeathObservation {
    /// Tick that produced the event.
    pub tick: u32,
    /// Entity credited with the kill, when one was reported.
    pub killer: Option<EntityId>,
    /// Whether the death was a deny.
    pub denied: bool,
    /// Gold paid directly for the death.
    pub gold: i32,
}

/// One observed completed ability cast.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AbilityCastObservation {
    /// Tick that produced the event.
    pub tick: u32,
    /// Ability reported by the event.
    pub ability: AbilityId,
}

/// A physical non-critical damage event that might be an attack landing.
///
/// The wire does not identify attack damage. This value is only a candidate and
/// must not be used as proof of an attack phase. A same-tick reported ability
/// cast is excluded, but an unreported physical ability can remain ambiguous.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PossibleAttackLanded {
    /// Tick of the candidate damage event.
    pub tick: u32,
    /// Entity that received the candidate hit.
    pub target: EntityId,
}

/// Bounded memory for one entity, keyed by its full generational handle.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EntityTrack {
    /// Full opaque entity handle.
    pub id: EntityId,
    /// Most recent visible unit data.
    pub unit: UnitView,
    /// Position from the preceding visible observation.
    pub previous_pos: Vec2,
    /// Tick from the preceding visible observation.
    pub previous_seen_tick: u32,
    /// Tick of the most recent visible observation.
    pub last_seen_tick: u32,
    /// Exact displacement and elapsed ticks, absent before a second observation.
    pub velocity: Option<VelocityEstimate>,
    /// Health change since the preceding visible observation.
    pub hp_delta: i64,
    /// Mana change since the preceding visible observation.
    pub mana_delta: i64,
    /// Whether the entity is present in the current snapshot.
    pub visible: bool,
    /// Latest damage dealt by this entity.
    pub last_damage_dealt: Option<DamageObservation>,
    /// Latest damage taken by this entity.
    pub last_damage_taken: Option<DamageObservation>,
    /// Latest healing done by this entity.
    pub last_heal_dealt: Option<HealObservation>,
    /// Latest healing received by this entity.
    pub last_heal_received: Option<HealObservation>,
    /// Latest death reported for this entity.
    pub last_death: Option<DeathObservation>,
    /// Latest completed ability cast reported for this entity.
    pub last_ability_cast: Option<AbilityCastObservation>,
    /// Latest damage event that can only be treated as a possible landed attack.
    pub last_possible_attack_landed: Option<PossibleAttackLanded>,
}

/// One event retained with its game tick.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ObservedEvent {
    /// Tick that produced the event.
    pub tick: u32,
    /// Event visible to this seat.
    pub kind: EventKind,
}

/// Saturating public scoreboard totals for one team.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct TeamPublicSummary {
    /// Sum of public experience values.
    pub xp: i64,
    /// Sum of public hero levels.
    pub levels: u64,
    /// Sum of kills.
    pub kills: u64,
    /// Sum of deaths.
    pub deaths: u64,
    /// Sum of assists.
    pub assists: u64,
    /// Sum of last hits.
    pub last_hits: u64,
    /// Sum of denies.
    pub denies: u64,
}

/// Copyable global state derived from one snapshot.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct GlobalSummary {
    /// Snapshot tick.
    pub tick: u32,
    /// Current own hero health, or zero while no body is present.
    pub own_hp: i32,
    /// Current own hero maximum health, or zero while no body is present.
    pub own_max_hp: i32,
    /// Whether the own hero body supplies health in this summary.
    pub own_hp_present: bool,
    /// Current own hero mana, or zero while no body is present.
    pub own_mana: i32,
    /// Current own hero maximum mana, or zero when mana is not applicable.
    pub own_max_mana: i32,
    /// Whether the own hero body has a mana pool in this summary.
    pub own_mana_present: bool,
    /// Own public hero level.
    pub own_level: u8,
    /// Own unspent gold.
    pub own_gold: i32,
    /// Own ticks until respawn.
    pub own_respawn_left: u32,
    /// Number of currently visible allied units.
    pub visible_allied_units: u32,
    /// Number of currently visible enemy units.
    pub visible_enemy_units: u32,
    /// Public totals for the allied team.
    pub allied: TeamPublicSummary,
    /// Public totals for the enemy team.
    pub enemy: TeamPublicSummary,
    /// Visible allied structure health.
    pub allied_structure_hp: i64,
    /// Visible enemy structure health.
    pub enemy_structure_hp: i64,
    /// Whether observed structure destruction has a baseline.
    pub destroyed_structures_present: bool,
    /// Allied structures absent after they were observed.
    pub allied_structures_destroyed: u32,
    /// Enemy structures absent after they were observed.
    pub enemy_structures_destroyed: u32,
}

/// A rejected tracker input.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TrackerError {
    /// A bounded vector exceeded its contract.
    LimitExceeded {
        /// Input field name.
        field: &'static str,
        /// Supplied number of entries.
        actual: usize,
        /// Maximum accepted entries.
        limit: usize,
    },
    /// The process exhausted unique tracker lineage identities.
    LineageExhausted,
    /// Match map is not implemented by drysua.
    UnsupportedMap(u16),
    /// Match tick rate was zero.
    ZeroTickRate,
    /// Seat count was outside the supported interval.
    SeatCount(usize),
    /// Own seat was outside the supported interval.
    OwnSlotOutOfRange(u8),
    /// Match metadata did not contain the own seat.
    MissingOwnPick(u8),
    /// Own seat did not pick Shadow Fiend.
    WrongOwnHero(HeroId),
    /// Own seat had no playable team.
    InvalidOwnTeam(Team),
    /// Match metadata contained a repeated slot.
    DuplicatePickSlot(u8),
    /// Match metadata contained an out-of-range slot.
    PickSlotOutOfRange(u8),
    /// Terrain axis was outside the supported interval.
    TerrainAxis(u32),
    /// Terrain run lengths did not cover the terrain grid.
    TerrainCoverage { actual: u64, expected: u64 },
    /// A terrain run had zero length.
    ZeroTerrainRun(usize),
    /// An opaque cell was outside the terrain grid.
    OpaqueCellOutOfRange { x: u16, y: u16, cells: u32 },
    /// A geometry input was outside the fixed-point map extent.
    PositionOutOfMap {
        field: &'static str,
        index: usize,
        x_raw: i32,
        y_raw: i32,
        maximum_raw: i64,
    },
    /// Snapshot viewer was absent or belonged to a different team.
    WrongViewer(Option<Team>, Team),
    /// Snapshot tick did not strictly increase.
    SnapshotTick { incoming: u32, current: u32 },
    /// Snapshot omitted the own scoreboard row.
    MissingOwnPlayer(u8),
    /// Own gold was hidden in a seat-specific snapshot.
    MissingOwnGold,
    /// Own stash was hidden in a seat-specific snapshot.
    MissingOwnStash,
    /// Own live hero handle was absent from visible units.
    MissingOwnHero(EntityId),
    /// Own live hero unit had inconsistent identity data.
    InvalidOwnHero(EntityId),
    /// A visible hero claimed the own seat without matching its scoreboard body.
    AmbiguousOwnHero {
        scoreboard: Option<EntityId>,
        visible: EntityId,
    },
    /// More than one visible courier claimed the own seat.
    AmbiguousOwnCourier { first: EntityId, second: EntityId },
    /// A full entity handle occurred more than once in visible units.
    DuplicateUnit(EntityId),
    /// A full entity handle occurred more than once in visible projectiles.
    DuplicateProjectile(EntityId),
    /// A full entity handle occurred more than once in visible loot.
    DuplicateLoot(EntityId),
    /// A full seat handle occurred more than once in scoreboard rows.
    DuplicatePlayer(u8),
    /// Scoreboard rows were not sorted by slot.
    UnsortedPlayers,
    /// A match roster row was absent from the scoreboard.
    MissingRosterPlayer(u8),
    /// A scoreboard row did not occur in the match roster.
    UnknownRosterPlayer(u8),
    /// A scoreboard row had a team different from the match roster.
    WrongRosterTeam {
        /// Player slot.
        slot: u8,
        /// Team supplied by the snapshot.
        actual: Team,
        /// Team selected in match metadata.
        expected: Team,
    },
    /// A scoreboard row had a hero different from the match roster.
    WrongRosterHero {
        /// Player slot.
        slot: u8,
        /// Hero supplied by the snapshot.
        actual: HeroId,
        /// Hero selected in match metadata.
        expected: HeroId,
    },
    /// Visible units were not sorted by full entity handle.
    UnsortedUnits,
    /// A tree index did not refer to static match trees.
    InvalidFelledTree(u32),
    /// Position displacement did not fit the wire vector type.
    PositionDeltaOverflow(EntityId),
    /// Event batch ticks did not strictly increase.
    EventTickNotIncreasing { incoming: u32, previous: u32 },
}

impl fmt::Display for TrackerError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::LimitExceeded { .. }
            | Self::LineageExhausted
            | Self::UnsupportedMap(_)
            | Self::ZeroTickRate
            | Self::SeatCount(_)
            | Self::OwnSlotOutOfRange(_)
            | Self::MissingOwnPick(_)
            | Self::WrongOwnHero(_)
            | Self::InvalidOwnTeam(_)
            | Self::DuplicatePickSlot(_)
            | Self::PickSlotOutOfRange(_)
            | Self::TerrainAxis(_)
            | Self::TerrainCoverage { .. }
            | Self::ZeroTerrainRun(_)
            | Self::OpaqueCellOutOfRange { .. }
            | Self::PositionOutOfMap { .. } => fmt_match_error(self, formatter),
            Self::WrongViewer(_, _)
            | Self::SnapshotTick { .. }
            | Self::MissingOwnPlayer(_)
            | Self::MissingOwnGold
            | Self::MissingOwnStash
            | Self::MissingOwnHero(_)
            | Self::InvalidOwnHero(_)
            | Self::AmbiguousOwnHero { .. }
            | Self::AmbiguousOwnCourier { .. } => fmt_own_state_error(self, formatter),
            Self::DuplicateUnit(_)
            | Self::DuplicateProjectile(_)
            | Self::DuplicateLoot(_)
            | Self::DuplicatePlayer(_)
            | Self::UnsortedPlayers
            | Self::MissingRosterPlayer(_)
            | Self::UnknownRosterPlayer(_)
            | Self::WrongRosterTeam { .. }
            | Self::WrongRosterHero { .. } => fmt_roster_error(self, formatter),
            Self::UnsortedUnits
            | Self::InvalidFelledTree(_)
            | Self::PositionDeltaOverflow(_)
            | Self::EventTickNotIncreasing { .. } => fmt_stream_error(self, formatter),
        }
    }
}

fn fmt_match_error(error: &TrackerError, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    match error {
        TrackerError::LimitExceeded {
            field,
            actual,
            limit,
        } => {
            write!(formatter, "{field} has {actual} entries; limit is {limit}")
        }
        TrackerError::LineageExhausted => {
            formatter.write_str("StateTracker lineage identity space is exhausted")
        }
        TrackerError::UnsupportedMap(map) => write!(
            formatter,
            "unsupported map MapId({map}); expected MapId(0) or MapId(1)"
        ),
        TrackerError::ZeroTickRate => formatter.write_str("MatchInfo.tick_rate must be positive"),
        TrackerError::SeatCount(actual) => write!(
            formatter,
            "MatchInfo.picks has {actual} seats; expected 1..={MAX_SEATS}"
        ),
        TrackerError::OwnSlotOutOfRange(slot) => write!(
            formatter,
            "own SlotId({slot}) is outside supported seats 0..{MAX_SEATS}"
        ),
        TrackerError::MissingOwnPick(slot) => {
            write!(formatter, "MatchInfo.picks has no own SlotId({slot})")
        }
        TrackerError::WrongOwnHero(hero) => write!(
            formatter,
            "own slot picked HeroId({}), expected Shadow Fiend HeroId({})",
            hero.0, SHADOW_FIEND.0
        ),
        TrackerError::InvalidOwnTeam(team) => {
            write!(formatter, "own slot has non-playable team {team:?}")
        }
        TrackerError::DuplicatePickSlot(slot) => {
            write!(formatter, "MatchInfo.picks repeats SlotId({slot})")
        }
        TrackerError::PickSlotOutOfRange(slot) => write!(
            formatter,
            "MatchInfo.picks contains unsupported SlotId({slot})"
        ),
        TrackerError::TerrainAxis(cells) => write!(
            formatter,
            "MatchInfo.terrain_cells is {cells}; expected 1..={MAX_TERRAIN_AXIS}"
        ),
        TrackerError::TerrainCoverage { actual, expected } => write!(
            formatter,
            "MatchInfo.terrain_rle covers {actual} cells; expected {expected}"
        ),
        TrackerError::ZeroTerrainRun(index) => write!(
            formatter,
            "MatchInfo.terrain_rle entry {index} has zero run length"
        ),
        TrackerError::OpaqueCellOutOfRange { x, y, cells } => write!(
            formatter,
            "MatchInfo.opaque_cells contains ({x}, {y}) outside {cells}x{cells} terrain"
        ),
        TrackerError::PositionOutOfMap {
            field,
            index,
            x_raw,
            y_raw,
            maximum_raw,
        } => write!(
            formatter,
            "{field}[{index}] position raw ({x_raw}, {y_raw}) is outside 0..={maximum_raw}"
        ),
        _ => Err(fmt::Error),
    }
}

fn fmt_own_state_error(error: &TrackerError, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    match error {
        TrackerError::WrongViewer(actual, expected) => write!(
            formatter,
            "snapshot viewer {actual:?} differs from tracker team {expected:?}"
        ),
        TrackerError::SnapshotTick { incoming, current } => write!(
            formatter,
            "snapshot tick {incoming} does not follow current tick {current}"
        ),
        TrackerError::MissingOwnPlayer(slot) => {
            write!(formatter, "snapshot players has no own SlotId({slot})")
        }
        TrackerError::MissingOwnGold => {
            formatter.write_str("own player gold is absent in seat-specific snapshot")
        }
        TrackerError::MissingOwnStash => {
            formatter.write_str("own player stash is absent in seat-specific snapshot")
        }
        TrackerError::MissingOwnHero(id) => write!(
            formatter,
            "own live hero EntityId({}, {}) is absent from visible units",
            id.idx, id.generation
        ),
        TrackerError::InvalidOwnHero(id) => write!(
            formatter,
            "own live hero EntityId({}, {}) has inconsistent kind, team, owner, or hero",
            id.idx, id.generation
        ),
        TrackerError::AmbiguousOwnHero {
            scoreboard,
            visible,
        } => match scoreboard {
            Some(scoreboard) => write!(
                formatter,
                "own slot has visible hero EntityId({}, {}) besides scoreboard hero EntityId({}, {})",
                visible.idx, visible.generation, scoreboard.idx, scoreboard.generation
            ),
            None => write!(
                formatter,
                "own slot has visible hero EntityId({}, {}) while scoreboard body is absent",
                visible.idx, visible.generation
            ),
        },
        TrackerError::AmbiguousOwnCourier { first, second } => write!(
            formatter,
            "own slot has ambiguous couriers EntityId({}, {}) and EntityId({}, {})",
            first.idx, first.generation, second.idx, second.generation
        ),
        _ => Err(fmt::Error),
    }
}

fn fmt_roster_error(error: &TrackerError, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    match error {
        TrackerError::DuplicateUnit(id) => write!(
            formatter,
            "snapshot units repeats EntityId({}, {})",
            id.idx, id.generation
        ),
        TrackerError::DuplicateProjectile(id) => write!(
            formatter,
            "snapshot projectiles repeats EntityId({}, {})",
            id.idx, id.generation
        ),
        TrackerError::DuplicateLoot(id) => write!(
            formatter,
            "snapshot loot repeats EntityId({}, {})",
            id.idx, id.generation
        ),
        TrackerError::DuplicatePlayer(slot) => {
            write!(formatter, "snapshot players repeats SlotId({slot})")
        }
        TrackerError::UnsortedPlayers => {
            formatter.write_str("snapshot players are not sorted by SlotId")
        }
        TrackerError::MissingRosterPlayer(slot) => write!(
            formatter,
            "snapshot players has no MatchInfo pick SlotId({slot})"
        ),
        TrackerError::UnknownRosterPlayer(slot) => write!(
            formatter,
            "snapshot players contains unknown SlotId({slot})"
        ),
        TrackerError::WrongRosterTeam {
            slot,
            actual,
            expected,
        } => write!(
            formatter,
            "snapshot player SlotId({slot}) team {actual:?} differs from MatchInfo pick {expected:?}"
        ),
        TrackerError::WrongRosterHero {
            slot,
            actual,
            expected,
        } => write!(
            formatter,
            "snapshot player SlotId({slot}) HeroId({}) differs from MatchInfo pick HeroId({})",
            actual.0, expected.0
        ),
        _ => Err(fmt::Error),
    }
}

fn fmt_stream_error(error: &TrackerError, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    match error {
        TrackerError::UnsortedUnits => {
            formatter.write_str("snapshot units are not sorted by full EntityId")
        }
        TrackerError::InvalidFelledTree(index) => write!(
            formatter,
            "snapshot felled tree index {index} is outside static tree list"
        ),
        TrackerError::PositionDeltaOverflow(id) => write!(
            formatter,
            "position delta for EntityId({}, {}) exceeds Vec2 range",
            id.idx, id.generation
        ),
        TrackerError::EventTickNotIncreasing { incoming, previous } => write!(
            formatter,
            "event batch tick {incoming} must be greater than last event tick {previous}"
        ),
        _ => Err(fmt::Error),
    }
}

impl Error for TrackerError {}

/// Bounded state memory built only from one seat's public match stream.
pub struct StateTracker {
    lineage: NonZeroU64,
    revision: u64,
    slot: SlotId,
    team: Team,
    metadata: MatchMetadata,
    static_trees: Vec<Vec2>,
    terrain_rle: Vec<(u16, u8)>,
    opaque_cells: Vec<(u16, u16)>,
    terrain: Vec<u8>,
    opaque: Vec<bool>,
    shop: Vec<ShopEntry>,
    roster: Vec<Pick>,
    previous_snapshot: Option<WorldView>,
    current: Option<WorldView>,
    entities: Vec<EntityTrack>,
    recent_events: VecDeque<ObservedEvent>,
    snapshot_events: VecDeque<ObservedEvent>,
    summaries: VecDeque<GlobalSummary>,
    last_event_tick: Option<u32>,
    peak_allied_structures: Option<u32>,
    peak_enemy_structures: Option<u32>,
    structure_baseline_complete: bool,
}

impl Clone for StateTracker {
    fn clone(&self) -> Self {
        let lineage = allocate_tracker_lineage();
        assert!(
            lineage.is_ok(),
            "cloning StateTracker exhausted every nonzero u64 process-wide lineage identity"
        );
        Self {
            lineage: lineage.expect("lineage availability was asserted"),
            revision: self.revision,
            slot: self.slot,
            team: self.team,
            metadata: self.metadata,
            static_trees: self.static_trees.clone(),
            terrain_rle: self.terrain_rle.clone(),
            opaque_cells: self.opaque_cells.clone(),
            terrain: self.terrain.clone(),
            opaque: self.opaque.clone(),
            shop: self.shop.clone(),
            roster: self.roster.clone(),
            previous_snapshot: self.previous_snapshot.clone(),
            current: self.current.clone(),
            entities: self.entities.clone(),
            recent_events: self.recent_events.clone(),
            snapshot_events: self.snapshot_events.clone(),
            summaries: self.summaries.clone(),
            last_event_tick: self.last_event_tick,
            peak_allied_structures: self.peak_allied_structures,
            peak_enemy_structures: self.peak_enemy_structures,
            structure_baseline_complete: self.structure_baseline_complete,
        }
    }
}

impl StateTracker {
    /// Creates an empty tracker after validating all static match inputs.
    pub fn new(slot: SlotId, info: &MatchInfo) -> Result<Self, TrackerError> {
        let team = validate_match_info(slot, info)?;
        let lineage = allocate_tracker_lineage()?;
        let mut roster = info.picks.clone();
        roster.sort_by_key(|pick| pick.slot);
        let metadata = MatchMetadata {
            map: info.map,
            tick_rate: info.tick_rate,
            pregame_ticks: info.pregame_ticks,
            terrain_cells: info.terrain_cells,
            mode: info.mode,
            seats: info.picks.len() as u8,
        };
        let (terrain, opaque) = decode_terrain(info);
        Ok(Self {
            lineage,
            revision: 0,
            slot,
            team,
            metadata,
            static_trees: info.trees.clone(),
            terrain_rle: info.terrain_rle.clone(),
            opaque_cells: info.opaque_cells.clone(),
            terrain,
            opaque,
            shop: info.shop.clone(),
            roster,
            previous_snapshot: None,
            current: None,
            entities: Vec::with_capacity(MAX_TRACKED_ENTITIES),
            recent_events: VecDeque::with_capacity(MAX_RECENT_EVENTS),
            snapshot_events: VecDeque::with_capacity(MAX_RECENT_EVENTS),
            summaries: VecDeque::with_capacity(MAX_HISTORY_SUMMARIES),
            last_event_tick: None,
            peak_allied_structures: None,
            peak_enemy_structures: None,
            structure_baseline_complete: false,
        })
    }

    /// Own seat.
    pub const fn slot(&self) -> SlotId {
        self.slot
    }

    /// Own playable team.
    pub const fn team(&self) -> Team {
        self.team
    }

    pub(crate) const fn lineage(&self) -> NonZeroU64 {
        self.lineage
    }

    /// Public feature-oriented match metadata, without match ID.
    pub const fn metadata(&self) -> MatchMetadata {
        self.metadata
    }

    /// Static tree positions from match metadata.
    pub fn static_trees(&self) -> &[Vec2] {
        &self.static_trees
    }

    /// Bounded run-length encoded terrain from match metadata.
    pub fn terrain_rle(&self) -> &[(u16, u8)] {
        &self.terrain_rle
    }

    /// Bounded static sight blockers, including map-start tree cells.
    pub fn opaque_cells(&self) -> &[(u16, u16)] {
        &self.opaque_cells
    }

    /// Whether public terrain and current allied vision prove `target` visible.
    pub fn position_visible_to_own_seat(&self, target: Vec2) -> bool {
        let Some(view) = self.current.as_ref() else {
            return false;
        };
        let axis = self.metadata.terrain_cells as usize;
        view.units
            .iter()
            .filter(|unit| {
                unit.team == self.team
                    && unit.hp > 0
                    && unit.statuses.bits & bota_proto::StatusFlags::DEAD == 0
            })
            .any(|viewer| position_visible_from(&self.terrain, &self.opaque, axis, viewer, target))
    }

    /// Whether a live allied unit occupies the target cell or an adjacent cell.
    ///
    /// This is the conservative proof accepted for dynamic tree deltas. It uses
    /// only current allied bodies and geometry, so no other planted or felled
    /// list entry can make a delta observable.
    pub fn position_locally_observable_to_own_seat(&self, target: Vec2) -> bool {
        let Some(view) = self.current.as_ref() else {
            return false;
        };
        let axis = self.metadata.terrain_cells as usize;
        let Some(target_cell) = position_cell_xy(axis, target) else {
            return false;
        };
        view.units.iter().any(|unit| {
            unit.team == self.team
                && unit.hp > 0
                && unit.statuses.bits & bota_proto::StatusFlags::DEAD == 0
                && position_cell_xy(axis, unit.pos).is_some_and(|viewer_cell| {
                    viewer_cell.0.abs_diff(target_cell.0) <= 1
                        && viewer_cell.1.abs_diff(target_cell.1) <= 1
                })
        })
    }

    /// Bounded static shop entries.
    pub fn shop(&self) -> &[ShopEntry] {
        &self.shop
    }

    /// Latest validated seat-specific snapshot.
    pub fn current(&self) -> Option<&WorldView> {
        self.current.as_ref()
    }

    /// One remembered entity by its full opaque handle.
    pub fn entity(&self, id: EntityId) -> Option<&EntityTrack> {
        self.entities
            .binary_search_by_key(&id, |entity| entity.id)
            .ok()
            .map(|index| &self.entities[index])
    }

    /// All remembered entities, sorted by full opaque handle.
    pub fn entities(&self) -> &[EntityTrack] {
        &self.entities
    }

    /// Recent visible events in stream order.
    pub fn recent_events(&self) -> &VecDeque<ObservedEvent> {
        &self.recent_events
    }

    pub(crate) fn snapshot_events(&self) -> &VecDeque<ObservedEvent> {
        &self.snapshot_events
    }

    /// Seven summaries selected by game-tick age, oldest first.
    pub fn history(&self) -> [GlobalSummary; HISTORY_AGES.len()] {
        std::array::from_fn(|index| self.summary_at_age(HISTORY_AGES[index]))
    }

    /// Latest seat-safe summary produced from the current snapshot.
    pub fn latest_summary(&self) -> Option<GlobalSummary> {
        self.summaries.back().copied()
    }

    /// Own scoreboard row from the current snapshot.
    pub fn own_player(&self) -> Option<&PlayerView> {
        self.current
            .as_ref()?
            .players
            .iter()
            .find(|player| player.slot == self.slot)
    }

    /// Own live Shadow Fiend body from the current snapshot.
    pub fn own_hero(&self) -> Option<&UnitView> {
        let id = self.own_player()?.unit?;
        let current = self.current.as_ref()?;
        let index = current
            .units
            .binary_search_by_key(&id, |unit| unit.id)
            .ok()?;
        Some(&current.units[index])
    }

    /// Own currently visible courier.
    pub fn own_courier(&self) -> Option<&UnitView> {
        self.current.as_ref()?.units.iter().find(|unit| {
            unit.kind == UnitKind::Courier
                && unit.team == self.team
                && unit.owner == Some(self.slot)
        })
    }

    pub(crate) fn static_provenance(&self) -> StaticTrackerProvenance {
        StaticTrackerProvenance {
            slot: self.slot,
            team: self.team,
            metadata: self.metadata,
            static_trees: self.static_trees.clone(),
            terrain_rle: self.terrain_rle.clone(),
            opaque_cells: self.opaque_cells.clone(),
            shop: self.shop.clone(),
            roster: self.roster.clone(),
        }
    }

    pub(crate) fn provenance(&self) -> TrackerProvenance {
        TrackerProvenance {
            lineage: self.lineage,
            revision: self.revision,
            static_data: self.static_provenance(),
            previous_snapshot: self.previous_snapshot.clone(),
            snapshot: self
                .current
                .clone()
                .expect("snapshot provenance requires a snapshot"),
            entities: self.entities.clone(),
            recent_events: self.recent_events.clone(),
            snapshot_events: self.snapshot_events.clone(),
            summaries: self.summaries.clone(),
            last_event_tick: self.last_event_tick,
            peak_allied_structures: self.peak_allied_structures,
            peak_enemy_structures: self.peak_enemy_structures,
            structure_baseline_complete: self.structure_baseline_complete,
        }
    }

    /// Validates and records one strictly newer seat-specific snapshot.
    pub fn observe_snapshot(&mut self, view: &WorldView) -> Result<(), TrackerError> {
        validate_snapshot(self, view)?;
        validate_position_deltas(&self.entities, view)?;
        if self.peak_allied_structures.is_none() {
            self.structure_baseline_complete = view.tick <= self.metadata.pregame_ticks;
        }
        let structure_counts = structure_counts(self.team, view);
        let peak_allied = update_peak(&mut self.peak_allied_structures, structure_counts.0);
        let peak_enemy = update_peak(&mut self.peak_enemy_structures, structure_counts.1);
        let summary = build_summary(
            self.slot,
            self.team,
            view,
            (peak_allied, peak_enemy),
            structure_counts,
            self.structure_baseline_complete,
        );
        self.update_entities(view);
        self.push_summary(summary);
        self.snapshot_events.clear();
        self.snapshot_events.extend(
            self.recent_events
                .iter()
                .filter(|event| event.tick < view.tick)
                .cloned(),
        );
        self.previous_snapshot = self.current.clone();
        self.current = Some(view.clone());
        self.advance_revision();
        Ok(())
    }

    /// Records one batch from the independent strictly increasing event stream.
    pub fn observe_events(&mut self, tick: u32, events: &[EventKind]) -> Result<(), TrackerError> {
        validate_event_batch_limit(events.len())?;
        if let Some(previous) = self.last_event_tick
            && tick <= previous
        {
            return Err(TrackerError::EventTickNotIncreasing {
                incoming: tick,
                previous,
            });
        }
        self.update_casts(tick, events);
        for event in events {
            self.update_from_event(tick, event);
            if self.recent_events.len() == MAX_RECENT_EVENTS {
                self.recent_events.pop_front();
            }
            self.recent_events.push_back(ObservedEvent {
                tick,
                kind: event.clone(),
            });
            self.record_snapshot_event(tick, event);
        }
        self.last_event_tick = Some(tick);
        self.advance_revision();
        Ok(())
    }

    fn advance_revision(&mut self) {
        self.revision = self
            .revision
            .checked_add(1)
            .expect("strict u32 snapshot and event ticks bound tracker revisions below u64");
    }

    fn record_snapshot_event(&mut self, tick: u32, event: &EventKind) {
        if self.current.as_ref().is_none_or(|view| tick >= view.tick) {
            return;
        }
        if self.snapshot_events.len() == MAX_RECENT_EVENTS {
            self.snapshot_events.pop_front();
        }
        self.snapshot_events.push_back(ObservedEvent {
            tick,
            kind: event.clone(),
        });
    }

    fn update_casts(&mut self, tick: u32, events: &[EventKind]) {
        for event in events {
            if let EventKind::AbilityCast { caster, ability } = *event
                && let Some(entity) = self.entity_mut(caster)
            {
                entity.last_ability_cast = Some(AbilityCastObservation { tick, ability });
            }
        }
    }

    fn update_entities(&mut self, view: &WorldView) {
        self.remove_replaced_own_bodies(view);
        self.entities
            .retain(|entity| view.tick.saturating_sub(entity.last_seen_tick) <= HISTORY_TICKS);
        self.make_entity_room(view);
        for entity in &mut self.entities {
            entity.visible = false;
        }
        for unit in &view.units {
            if let Ok(index) = self
                .entities
                .binary_search_by_key(&unit.id, |entity| entity.id)
            {
                update_entity(&mut self.entities[index], view.tick, unit);
            }
        }
        for unit in &view.units {
            if self
                .entities
                .binary_search_by_key(&unit.id, |entity| entity.id)
                .is_err()
            {
                let index = self
                    .entities
                    .binary_search_by_key(&unit.id, |entity| entity.id)
                    .expect_err("new entity cannot already exist");
                self.entities.insert(index, new_entity(view.tick, unit));
            }
        }
        assert!(self.entities.len() <= MAX_TRACKED_ENTITIES);
    }

    fn remove_replaced_own_bodies(&mut self, view: &WorldView) {
        let slot = self.slot;
        let team = self.team;
        let own_hero = view
            .players
            .iter()
            .find(|player| player.slot == self.slot)
            .and_then(|player| player.unit);
        let own_courier = view
            .units
            .iter()
            .find(|unit| is_own_courier(self, unit))
            .map(|unit| unit.id);
        self.entities.retain(|track| {
            let own_body = matches!(track.unit.kind, UnitKind::Hero | UnitKind::Courier)
                && track.unit.team == team
                && track.unit.owner == Some(slot);
            if !own_body {
                return true;
            }
            match track.unit.kind {
                UnitKind::Hero => Some(track.id) == own_hero || own_hero.is_none(),
                UnitKind::Courier => Some(track.id) == own_courier || own_courier.is_none(),
                _ => true,
            }
        });
    }

    fn make_entity_room(&mut self, view: &WorldView) {
        let new_count = view
            .units
            .iter()
            .filter(|unit| {
                self.entities
                    .binary_search_by_key(&unit.id, |entity| entity.id)
                    .is_err()
            })
            .count();
        let mut required = self
            .entities
            .len()
            .saturating_add(new_count)
            .saturating_sub(MAX_TRACKED_ENTITIES);
        while required > 0 {
            let oldest = self
                .entities
                .iter()
                .filter(|track| !snapshot_contains(view, track.id))
                .map(|track| track.last_seen_tick)
                .min()
                .expect("validated visible-unit bound guarantees an invisible eviction cohort");
            let before = self.entities.len();
            self.entities.retain(|track| {
                track.last_seen_tick != oldest || snapshot_contains(view, track.id)
            });
            let evicted = before - self.entities.len();
            assert!(evicted > 0);
            required = required.saturating_sub(evicted);
        }
    }

    fn update_from_event(&mut self, tick: u32, event: &EventKind) {
        match *event {
            EventKind::Damaged {
                source,
                target,
                amount,
                kind,
                crit,
            } => self.update_damage(tick, source, target, amount, kind, crit),
            EventKind::Healed {
                source,
                target,
                amount,
            } => {
                self.update_heal(tick, source, target, amount);
            }
            EventKind::Died {
                unit,
                killer,
                denied,
                gold,
            } => {
                if let Some(entity) = self.entity_mut(unit) {
                    entity.last_death = Some(DeathObservation {
                        tick,
                        killer,
                        denied,
                        gold,
                    });
                    entity.visible = false;
                }
            }
            EventKind::AbilityCast { .. } => {}
            EventKind::LevelUp { .. }
            | EventKind::ItemBought { .. }
            | EventKind::StructureDestroyed { .. } => {}
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn update_damage(
        &mut self,
        tick: u32,
        source: Option<EntityId>,
        target: EntityId,
        amount: i32,
        kind: DamageKind,
        crit: bool,
    ) {
        if let Some(source) = source
            && let Some(entity) = self.entity_mut(source)
        {
            entity.last_damage_dealt = Some(DamageObservation {
                tick,
                amount,
                kind,
                crit,
                counterpart: Some(target),
            });
            if kind == DamageKind::Physical
                && !crit
                && entity
                    .last_ability_cast
                    .is_none_or(|cast| cast.tick != tick)
            {
                entity.last_possible_attack_landed = Some(PossibleAttackLanded { tick, target });
            }
        }
        if let Some(entity) = self.entity_mut(target) {
            entity.last_damage_taken = Some(DamageObservation {
                tick,
                amount,
                kind,
                crit,
                counterpart: source,
            });
        }
    }

    fn update_heal(&mut self, tick: u32, source: Option<EntityId>, target: EntityId, amount: i32) {
        if let Some(source) = source
            && let Some(entity) = self.entity_mut(source)
        {
            entity.last_heal_dealt = Some(HealObservation {
                tick,
                amount,
                counterpart: Some(target),
            });
        }
        if let Some(entity) = self.entity_mut(target) {
            entity.last_heal_received = Some(HealObservation {
                tick,
                amount,
                counterpart: source,
            });
        }
    }

    fn entity_mut(&mut self, id: EntityId) -> Option<&mut EntityTrack> {
        let index = self
            .entities
            .binary_search_by_key(&id, |entity| entity.id)
            .ok()?;
        Some(&mut self.entities[index])
    }

    fn push_summary(&mut self, summary: GlobalSummary) {
        self.summaries.push_back(summary);
        let oldest_tick = summary.tick.saturating_sub(HISTORY_TICKS);
        while self.summaries.len() > 1 && self.summaries[1].tick <= oldest_tick {
            self.summaries.pop_front();
        }
        while self.summaries.len() > MAX_HISTORY_SUMMARIES {
            self.summaries.pop_front();
        }
    }

    fn summary_at_age(&self, age: u32) -> GlobalSummary {
        let newest = self.summaries.back().copied().unwrap_or_default();
        let target = newest.tick.saturating_sub(age);
        self.summaries
            .iter()
            .rev()
            .find(|summary| summary.tick <= target)
            .or_else(|| self.summaries.front())
            .copied()
            .unwrap_or_default()
    }
}

fn validate_match_info(slot: SlotId, info: &MatchInfo) -> Result<Team, TrackerError> {
    if slot.0 >= MAX_SEATS as u8 {
        return Err(TrackerError::OwnSlotOutOfRange(slot.0));
    }
    if !matches!(info.map, MapId(0) | MapId(1)) {
        return Err(TrackerError::UnsupportedMap(info.map.0));
    }
    if info.tick_rate == 0 {
        return Err(TrackerError::ZeroTickRate);
    }
    if info.picks.is_empty() || info.picks.len() > MAX_SEATS {
        return Err(TrackerError::SeatCount(info.picks.len()));
    }
    validate_picks(&info.picks)?;
    validate_static_inputs(info)?;
    let own = info
        .picks
        .iter()
        .find(|pick| pick.slot == slot)
        .ok_or(TrackerError::MissingOwnPick(slot.0))?;
    if own.hero != SHADOW_FIEND {
        return Err(TrackerError::WrongOwnHero(own.hero));
    }
    if !matches!(own.team, Team::Radiant | Team::Dire) {
        return Err(TrackerError::InvalidOwnTeam(own.team));
    }
    Ok(own.team)
}

fn validate_picks(picks: &[Pick]) -> Result<(), TrackerError> {
    for (index, pick) in picks.iter().enumerate() {
        if pick.slot.0 >= MAX_SEATS as u8 {
            return Err(TrackerError::PickSlotOutOfRange(pick.slot.0));
        }
        if picks[..index].iter().any(|other| other.slot == pick.slot) {
            return Err(TrackerError::DuplicatePickSlot(pick.slot.0));
        }
    }
    Ok(())
}

fn validate_static_inputs(info: &MatchInfo) -> Result<(), TrackerError> {
    check_limit("MatchInfo.trees", info.trees.len(), MAX_STATIC_TREES)?;
    check_limit(
        "MatchInfo.terrain_rle",
        info.terrain_rle.len(),
        MAX_TERRAIN_RUNS,
    )?;
    check_limit(
        "MatchInfo.opaque_cells",
        info.opaque_cells.len(),
        MAX_OPAQUE_CELLS,
    )?;
    check_limit("MatchInfo.shop", info.shop.len(), MAX_SHOP_ITEMS)?;
    if info.terrain_cells == 0 || info.terrain_cells > MAX_TERRAIN_AXIS {
        return Err(TrackerError::TerrainAxis(info.terrain_cells));
    }
    if let Some(index) = info.terrain_rle.iter().position(|(run, _)| *run == 0) {
        return Err(TrackerError::ZeroTerrainRun(index));
    }
    let expected = u64::from(info.terrain_cells) * u64::from(info.terrain_cells);
    let actual = info
        .terrain_rle
        .iter()
        .fold(0u64, |sum, (run, _)| sum.saturating_add(u64::from(*run)));
    if actual != expected {
        return Err(TrackerError::TerrainCoverage { actual, expected });
    }
    for &(x, y) in &info.opaque_cells {
        if u32::from(x) >= info.terrain_cells || u32::from(y) >= info.terrain_cells {
            return Err(TrackerError::OpaqueCellOutOfRange {
                x,
                y,
                cells: info.terrain_cells,
            });
        }
    }
    validate_positions(
        "MatchInfo.trees",
        &info.trees,
        map_maximum_raw(info.terrain_cells),
    )?;
    for entry in &info.shop {
        check_limit(
            "ShopEntry.components",
            entry.components.len(),
            MAX_SHOP_COMPONENTS,
        )?;
    }
    Ok(())
}

fn decode_terrain(info: &MatchInfo) -> (Vec<u8>, Vec<bool>) {
    let axis = info.terrain_cells as usize;
    let mut terrain = Vec::with_capacity(axis * axis);
    for &(run, cell) in &info.terrain_rle {
        terrain.resize(terrain.len() + usize::from(run), cell);
    }
    let mut opaque = vec![false; axis * axis];
    for &(x, y) in &info.opaque_cells {
        opaque[usize::from(y) * axis + usize::from(x)] = true;
    }
    debug_assert_eq!(terrain.len(), axis * axis);
    debug_assert_eq!(opaque.len(), axis * axis);
    (terrain, opaque)
}

fn validate_snapshot(tracker: &StateTracker, view: &WorldView) -> Result<(), TrackerError> {
    if view.viewer != Some(tracker.team) {
        return Err(TrackerError::WrongViewer(view.viewer, tracker.team));
    }
    if let Some(current) = &tracker.current
        && view.tick <= current.tick
    {
        return Err(TrackerError::SnapshotTick {
            incoming: view.tick,
            current: current.tick,
        });
    }
    validate_snapshot_limits(view)?;
    validate_snapshot_positions(tracker.metadata.terrain_cells, view)?;
    validate_units(view)?;
    validate_unique_dynamic_handles(view)?;
    validate_players(&tracker.roster, view)?;
    validate_trees(tracker.static_trees.len(), view)?;
    validate_own_state(tracker, view)
}

fn validate_unique_dynamic_handles(view: &WorldView) -> Result<(), TrackerError> {
    for (index, projectile) in view.projectiles.iter().enumerate() {
        if view.projectiles[..index]
            .iter()
            .any(|other| other.id == projectile.id)
        {
            return Err(TrackerError::DuplicateProjectile(projectile.id));
        }
    }
    for (index, loot) in view.loot.iter().enumerate() {
        if view.loot[..index].iter().any(|other| other.id == loot.id) {
            return Err(TrackerError::DuplicateLoot(loot.id));
        }
    }
    Ok(())
}

fn validate_snapshot_limits(view: &WorldView) -> Result<(), TrackerError> {
    check_limit("WorldView.units", view.units.len(), MAX_TRACKED_ENTITIES)?;
    check_limit(
        "WorldView.projectiles",
        view.projectiles.len(),
        MAX_PROJECTILES,
    )?;
    check_limit("WorldView.players", view.players.len(), MAX_SEATS)?;
    check_limit("WorldView.loot", view.loot.len(), MAX_LOOT)?;
    check_limit(
        "WorldView.felled_trees",
        view.felled_trees.len(),
        MAX_STATIC_TREES,
    )?;
    check_limit(
        "WorldView.planted_trees",
        view.planted_trees.len(),
        MAX_PLANTED_TREES,
    )?;
    Ok(())
}

fn validate_units(view: &WorldView) -> Result<(), TrackerError> {
    for (index, unit) in view.units.iter().enumerate() {
        if index > 0 {
            if view.units[index - 1].id == unit.id {
                return Err(TrackerError::DuplicateUnit(unit.id));
            }
            if view.units[index - 1].id > unit.id {
                return Err(TrackerError::UnsortedUnits);
            }
        }
        let ability_limit = if unit.owner.is_some() && unit.hero == Some(SHADOW_FIEND) {
            SHADOW_FIEND_ABILITY_SLOTS
        } else {
            MAX_ABILITY_SLOTS
        };
        check_limit("UnitView.abilities", unit.abilities.len(), ability_limit)?;
        check_limit("UnitView.items", unit.items.len(), HERO_ITEM_SLOTS)?;
        check_limit("UnitView.effects", unit.effects.len(), MAX_EFFECTS_PER_UNIT)?;
    }
    Ok(())
}

fn validate_players(roster: &[Pick], view: &WorldView) -> Result<(), TrackerError> {
    for (index, player) in view.players.iter().enumerate() {
        if index > 0 {
            if view.players[index - 1].slot == player.slot {
                return Err(TrackerError::DuplicatePlayer(player.slot.0));
            }
            if view.players[index - 1].slot > player.slot {
                return Err(TrackerError::UnsortedPlayers);
            }
        }
        if let Some(stash) = &player.stash {
            check_limit("PlayerView.stash", stash.len(), STASH_ITEM_SLOTS)?;
        }
        if let Some(kit) = &player.kit {
            let ability_limit = if player.hero == SHADOW_FIEND {
                SHADOW_FIEND_ABILITY_SLOTS
            } else {
                MAX_ABILITY_SLOTS
            };
            check_limit("Kit.abilities", kit.abilities.len(), ability_limit)?;
            check_limit("Kit.items", kit.items.len(), HERO_ITEM_SLOTS)?;
        }
    }
    validate_roster(roster, &view.players)
}

fn validate_roster(roster: &[Pick], players: &[PlayerView]) -> Result<(), TrackerError> {
    for player in players {
        let index = roster
            .binary_search_by_key(&player.slot, |pick| pick.slot)
            .map_err(|_| TrackerError::UnknownRosterPlayer(player.slot.0))?;
        let pick = &roster[index];
        validate_roster_row(pick, player)?;
    }
    for pick in roster {
        if players
            .binary_search_by_key(&pick.slot, |player| player.slot)
            .is_err()
        {
            return Err(TrackerError::MissingRosterPlayer(pick.slot.0));
        }
    }
    Ok(())
}

fn validate_roster_row(pick: &Pick, player: &PlayerView) -> Result<(), TrackerError> {
    if player.team != pick.team {
        return Err(TrackerError::WrongRosterTeam {
            slot: player.slot.0,
            actual: player.team,
            expected: pick.team,
        });
    }
    if player.hero != pick.hero {
        return Err(TrackerError::WrongRosterHero {
            slot: player.slot.0,
            actual: player.hero,
            expected: pick.hero,
        });
    }
    Ok(())
}

fn validate_trees(static_tree_count: usize, view: &WorldView) -> Result<(), TrackerError> {
    for index in &view.felled_trees {
        if usize::try_from(*index).map_or(true, |index| index >= static_tree_count) {
            return Err(TrackerError::InvalidFelledTree(*index));
        }
    }
    Ok(())
}

fn validate_own_state(tracker: &StateTracker, view: &WorldView) -> Result<(), TrackerError> {
    let player_index = view
        .players
        .binary_search_by_key(&tracker.slot, |player| player.slot)
        .map_err(|_| TrackerError::MissingOwnPlayer(tracker.slot.0))?;
    let player = &view.players[player_index];
    if player.gold.is_none() {
        return Err(TrackerError::MissingOwnGold);
    }
    let stash_items = player
        .stash
        .as_ref()
        .ok_or(TrackerError::MissingOwnStash)?
        .len();
    let body_items = if let Some(id) = player.unit {
        let unit = view
            .units
            .binary_search_by_key(&id, |unit| unit.id)
            .ok()
            .map(|index| &view.units[index])
            .ok_or(TrackerError::MissingOwnHero(id))?;
        if unit.kind != UnitKind::Hero
            || unit.team != tracker.team
            || unit.owner != Some(tracker.slot)
            || unit.hero != Some(SHADOW_FIEND)
        {
            return Err(TrackerError::InvalidOwnHero(id));
        }
        unit.items.len()
    } else {
        player.kit.as_ref().map_or(0, |kit| kit.items.len())
    };
    validate_own_hero_claims(tracker, view, player.unit)?;
    validate_own_courier(tracker, view)?;
    validate_own_item_slots(tracker, view, body_items, stash_items)
}

fn validate_own_hero_claims(
    tracker: &StateTracker,
    view: &WorldView,
    scoreboard: Option<EntityId>,
) -> Result<(), TrackerError> {
    for unit in &view.units {
        if unit.kind == UnitKind::Hero
            && unit.owner == Some(tracker.slot)
            && Some(unit.id) != scoreboard
        {
            return Err(TrackerError::AmbiguousOwnHero {
                scoreboard,
                visible: unit.id,
            });
        }
    }
    Ok(())
}

fn validate_own_courier(tracker: &StateTracker, view: &WorldView) -> Result<(), TrackerError> {
    let mut courier = None;
    for unit in &view.units {
        if !is_own_courier(tracker, unit) {
            continue;
        }
        if let Some(first) = courier {
            return Err(TrackerError::AmbiguousOwnCourier {
                first,
                second: unit.id,
            });
        }
        courier = Some(unit.id);
    }
    Ok(())
}

fn validate_own_item_slots(
    tracker: &StateTracker,
    view: &WorldView,
    body_items: usize,
    stash_items: usize,
) -> Result<(), TrackerError> {
    let mut courier_items = 0usize;
    for unit in &view.units {
        if unit.kind == UnitKind::Courier
            && unit.team == tracker.team
            && unit.owner == Some(tracker.slot)
        {
            check_limit("own courier items", unit.items.len(), COURIER_ITEM_SLOTS)?;
            courier_items = courier_items.saturating_add(unit.items.len());
        }
    }
    check_limit(
        "own hero, stash, and courier item slots",
        body_items
            .saturating_add(stash_items)
            .saturating_add(courier_items),
        OWN_ITEM_SLOTS,
    )
}

fn validate_position_deltas(
    entities: &[EntityTrack],
    view: &WorldView,
) -> Result<(), TrackerError> {
    for unit in &view.units {
        if let Ok(index) = entities.binary_search_by_key(&unit.id, |entity| entity.id) {
            let previous = entities[index].unit.pos;
            if unit.pos.x.checked_sub(previous.x).is_none()
                || unit.pos.y.checked_sub(previous.y).is_none()
            {
                return Err(TrackerError::PositionDeltaOverflow(unit.id));
            }
        }
    }
    Ok(())
}

fn new_entity(tick: u32, unit: &UnitView) -> EntityTrack {
    EntityTrack {
        id: unit.id,
        unit: unit.clone(),
        previous_pos: unit.pos,
        previous_seen_tick: tick,
        last_seen_tick: tick,
        velocity: None,
        hp_delta: 0,
        mana_delta: 0,
        visible: true,
        last_damage_dealt: None,
        last_damage_taken: None,
        last_heal_dealt: None,
        last_heal_received: None,
        last_death: None,
        last_ability_cast: None,
        last_possible_attack_landed: None,
    }
}

fn update_entity(entity: &mut EntityTrack, tick: u32, unit: &UnitView) {
    let previous_pos = entity.unit.pos;
    let previous_tick = entity.last_seen_tick;
    entity.previous_pos = previous_pos;
    entity.previous_seen_tick = previous_tick;
    entity.last_seen_tick = tick;
    entity.velocity = Some(VelocityEstimate {
        delta: Vec2 {
            x: unit
                .pos
                .x
                .checked_sub(previous_pos.x)
                .expect("position delta was validated"),
            y: unit
                .pos
                .y
                .checked_sub(previous_pos.y)
                .expect("position delta was validated"),
        },
        elapsed_ticks: tick - previous_tick,
    });
    entity.hp_delta = i64::from(unit.hp) - i64::from(entity.unit.hp);
    entity.mana_delta = i64::from(unit.mana) - i64::from(entity.unit.mana);
    entity.unit = unit.clone();
    entity.visible = true;
}

fn snapshot_contains(view: &WorldView, id: EntityId) -> bool {
    view.units.binary_search_by_key(&id, |unit| unit.id).is_ok()
}

fn build_summary(
    slot: SlotId,
    team: Team,
    view: &WorldView,
    peak_structures: (u32, u32),
    current_structures: (u32, u32),
    structure_baseline_complete: bool,
) -> GlobalSummary {
    let player = view
        .players
        .iter()
        .find(|player| player.slot == slot)
        .expect("own player was validated");
    let hero = player.unit.and_then(|id| {
        view.units
            .binary_search_by_key(&id, |unit| unit.id)
            .ok()
            .map(|index| &view.units[index])
    });
    let allied_destroyed = if structure_baseline_complete {
        peak_structures.0.saturating_sub(current_structures.0)
    } else {
        0
    };
    let enemy_destroyed = if structure_baseline_complete {
        peak_structures.1.saturating_sub(current_structures.1)
    } else {
        0
    };
    let mut summary = GlobalSummary {
        tick: view.tick,
        own_hp: hero.map_or(0, |unit| unit.hp),
        own_max_hp: hero.map_or(0, |unit| unit.max_hp),
        own_hp_present: hero.is_some(),
        own_mana: hero.map_or(0, |unit| unit.mana),
        own_max_mana: hero.map_or(0, |unit| unit.max_mana),
        own_mana_present: hero.is_some_and(|unit| unit.max_mana > 0),
        own_level: player.level,
        own_gold: player.gold.expect("own gold was validated"),
        own_respawn_left: player.respawn_left,
        destroyed_structures_present: structure_baseline_complete,
        allied_structures_destroyed: allied_destroyed,
        enemy_structures_destroyed: enemy_destroyed,
        ..GlobalSummary::default()
    };
    for row in &view.players {
        let totals = if row.team == team {
            &mut summary.allied
        } else if row.team == opposing(team) {
            &mut summary.enemy
        } else {
            continue;
        };
        add_player_summary(totals, row);
    }
    for unit in &view.units {
        add_unit_summary(&mut summary, team, unit);
    }
    summary
}

fn add_player_summary(summary: &mut TeamPublicSummary, player: &PlayerView) {
    summary.xp = summary.xp.saturating_add(i64::from(player.xp));
    summary.levels = summary.levels.saturating_add(u64::from(player.level));
    summary.kills = summary.kills.saturating_add(u64::from(player.kills));
    summary.deaths = summary.deaths.saturating_add(u64::from(player.deaths));
    summary.assists = summary.assists.saturating_add(u64::from(player.assists));
    summary.last_hits = summary
        .last_hits
        .saturating_add(u64::from(player.last_hits));
    summary.denies = summary.denies.saturating_add(u64::from(player.denies));
}

fn structure_counts(team: Team, view: &WorldView) -> (u32, u32) {
    let mut allied = 0u32;
    let mut enemy = 0u32;
    for unit in &view.units {
        if !is_structure(unit.kind) {
            continue;
        }
        if unit.team == team {
            allied = allied.saturating_add(1);
        } else if unit.team == opposing(team) {
            enemy = enemy.saturating_add(1);
        }
    }
    (allied, enemy)
}

fn update_peak(peak: &mut Option<u32>, current: u32) -> u32 {
    let updated = peak.map_or(current, |value| value.max(current));
    *peak = Some(updated);
    updated
}

fn add_unit_summary(summary: &mut GlobalSummary, team: Team, unit: &UnitView) {
    let hp = i64::from(unit.hp.max(0));
    if unit.team == team {
        summary.visible_allied_units = summary.visible_allied_units.saturating_add(1);
        if is_structure(unit.kind) {
            summary.allied_structure_hp = summary.allied_structure_hp.saturating_add(hp);
        }
    } else if unit.team == opposing(team) {
        summary.visible_enemy_units = summary.visible_enemy_units.saturating_add(1);
        if is_structure(unit.kind) {
            summary.enemy_structure_hp = summary.enemy_structure_hp.saturating_add(hp);
        }
    }
}

const fn opposing(team: Team) -> Team {
    match team {
        Team::Radiant => Team::Dire,
        Team::Dire => Team::Radiant,
        Team::Neutral => Team::Neutral,
    }
}

pub(crate) const fn is_structure(kind: UnitKind) -> bool {
    matches!(
        kind,
        UnitKind::Tower | UnitKind::Ancient | UnitKind::Barracks | UnitKind::Fountain
    )
}

fn check_limit(field: &'static str, actual: usize, limit: usize) -> Result<(), TrackerError> {
    if actual > limit {
        return Err(TrackerError::LimitExceeded {
            field,
            actual,
            limit,
        });
    }
    Ok(())
}

pub(crate) fn validate_event_batch_limit(event_count: usize) -> Result<(), TrackerError> {
    check_limit("event batch", event_count, MAX_EVENTS_PER_BATCH)
}

fn validate_snapshot_positions(cells: u32, view: &WorldView) -> Result<(), TrackerError> {
    let maximum = map_maximum_raw(cells);
    for (index, unit) in view.units.iter().enumerate() {
        validate_position("WorldView.units", index, unit.pos, maximum)?;
    }
    for (index, projectile) in view.projectiles.iter().enumerate() {
        validate_position("WorldView.projectiles", index, projectile.pos, maximum)?;
    }
    validate_positions("WorldView.planted_trees", &view.planted_trees, maximum)?;
    for (index, loot) in view.loot.iter().enumerate() {
        validate_position("WorldView.loot", index, loot.pos, maximum)?;
    }
    Ok(())
}

fn validate_positions(
    field: &'static str,
    positions: &[Vec2],
    maximum: i64,
) -> Result<(), TrackerError> {
    for (index, position) in positions.iter().enumerate() {
        validate_position(field, index, *position, maximum)?;
    }
    Ok(())
}

fn validate_position(
    field: &'static str,
    index: usize,
    position: Vec2,
    maximum: i64,
) -> Result<(), TrackerError> {
    let x = i64::from(position.x.raw);
    let y = i64::from(position.y.raw);
    if x < 0 || y < 0 || x > maximum || y > maximum {
        return Err(TrackerError::PositionOutOfMap {
            field,
            index,
            x_raw: position.x.raw,
            y_raw: position.y.raw,
            maximum_raw: maximum,
        });
    }
    Ok(())
}

pub(crate) fn map_maximum_raw(cells: u32) -> i64 {
    i64::from(cells)
        .saturating_mul(i64::from(TERRAIN_CELL_SIZE))
        .saturating_mul(i64::from(Fixed::ONE.raw))
        .saturating_sub(1)
        .min(i64::from(i32::MAX))
}

fn position_visible_from(
    terrain: &[u8],
    opaque: &[bool],
    axis: usize,
    viewer: &UnitView,
    target: Vec2,
) -> bool {
    if viewer.vision_radius.raw <= 0 || !viewer.pos.within(target, viewer.vision_radius) {
        return false;
    }
    let Some(from_cell) = position_cell(axis, viewer.pos) else {
        return false;
    };
    let Some(to_cell) = position_cell(axis, target) else {
        return false;
    };
    let viewer_tier = terrain[from_cell] & 0x3f;
    if terrain[to_cell] & 0x3f > viewer_tier {
        return false;
    }
    terrain_line_clear(terrain, opaque, axis, viewer.pos, target, viewer_tier)
}

fn terrain_line_clear(
    terrain: &[u8],
    opaque: &[bool],
    axis: usize,
    from: Vec2,
    to: Vec2,
    viewer_tier: u8,
) -> bool {
    let Some((from_x, from_y)) = position_cell_xy(axis, from) else {
        return false;
    };
    let Some((to_x, to_y)) = position_cell_xy(axis, to) else {
        return false;
    };
    let delta_x = i64::from(to.x.raw) - i64::from(from.x.raw);
    let delta_y = i64::from(to.y.raw) - i64::from(from.y.raw);
    traverse_terrain_line(
        terrain,
        opaque,
        axis,
        (from_x, from_y),
        (to_x, to_y),
        (from.x.raw, from.y.raw),
        (delta_x, delta_y),
        viewer_tier,
    )
}

#[allow(clippy::too_many_arguments)]
fn traverse_terrain_line(
    terrain: &[u8],
    opaque: &[bool],
    axis: usize,
    from: (usize, usize),
    to: (usize, usize),
    from_raw: (i32, i32),
    delta: (i64, i64),
    viewer_tier: u8,
) -> bool {
    let mut cell = from;
    let step = (delta.0.signum(), delta.1.signum());
    let mut boundary = first_boundaries(cell, from_raw, step);
    let maximum_steps = axis.saturating_mul(2).saturating_add(1);
    for _ in 0..maximum_steps {
        if cell == to {
            return true;
        }
        let ordering = crossing_order(boundary, delta);
        if ordering == std::cmp::Ordering::Equal
            && corner_blocks(terrain, opaque, axis, cell, step, viewer_tier)
        {
            return false;
        }
        if ordering != std::cmp::Ordering::Greater {
            let Some(next) = add_step(cell.0, step.0, axis) else {
                return false;
            };
            cell.0 = next;
            boundary.0 += terrain_cell_raw();
        }
        if ordering != std::cmp::Ordering::Less {
            let Some(next) = add_step(cell.1, step.1, axis) else {
                return false;
            };
            cell.1 = next;
            boundary.1 += terrain_cell_raw();
        }
        if cell != to && terrain_cell_blocks(terrain, opaque, axis, cell, viewer_tier) {
            return false;
        }
    }
    false
}

fn corner_blocks(
    terrain: &[u8],
    opaque: &[bool],
    axis: usize,
    cell: (usize, usize),
    step: (i64, i64),
    viewer_tier: u8,
) -> bool {
    let Some(side_x) = add_step(cell.0, step.0, axis) else {
        return true;
    };
    let Some(side_y) = add_step(cell.1, step.1, axis) else {
        return true;
    };
    terrain_cell_blocks(terrain, opaque, axis, (side_x, cell.1), viewer_tier)
        || terrain_cell_blocks(terrain, opaque, axis, (cell.0, side_y), viewer_tier)
}

fn position_cell(axis: usize, position: Vec2) -> Option<usize> {
    let (x, y) = position_cell_xy(axis, position)?;
    Some(y * axis + x)
}

fn position_cell_xy(axis: usize, position: Vec2) -> Option<(usize, usize)> {
    if position.x.raw < 0 || position.y.raw < 0 {
        return None;
    }
    let x = usize::try_from(position.x.to_int() / TERRAIN_CELL_SIZE).ok()?;
    let y = usize::try_from(position.y.to_int() / TERRAIN_CELL_SIZE).ok()?;
    (x < axis && y < axis).then_some((x, y))
}

fn first_boundaries(cell: (usize, usize), from_raw: (i32, i32), step: (i64, i64)) -> (i64, i64) {
    (
        boundary_distance(cell.0, from_raw.0, step.0),
        boundary_distance(cell.1, from_raw.1, step.1),
    )
}

fn boundary_distance(cell: usize, raw: i32, step: i64) -> i64 {
    if step == 0 {
        return i64::MAX;
    }
    let cell_start = i64::try_from(cell).expect("bounded cell") * terrain_cell_raw();
    if step > 0 {
        cell_start + terrain_cell_raw() - i64::from(raw)
    } else {
        i64::from(raw) - cell_start
    }
}

fn crossing_order(boundary: (i64, i64), delta: (i64, i64)) -> std::cmp::Ordering {
    if delta.0 == 0 {
        return std::cmp::Ordering::Greater;
    }
    if delta.1 == 0 {
        return std::cmp::Ordering::Less;
    }
    (boundary.0 * delta.1.abs()).cmp(&(boundary.1 * delta.0.abs()))
}

fn add_step(value: usize, step: i64, axis: usize) -> Option<usize> {
    let next = value.checked_add_signed(isize::try_from(step).ok()?)?;
    (next < axis).then_some(next)
}

fn terrain_cell_blocks(
    terrain: &[u8],
    opaque: &[bool],
    axis: usize,
    cell: (usize, usize),
    viewer_tier: u8,
) -> bool {
    let index = cell.1 * axis + cell.0;
    opaque[index] || terrain[index] & 0x3f > viewer_tier
}

const fn terrain_cell_raw() -> i64 {
    (TERRAIN_CELL_SIZE as i64) << Fixed::FRAC_BITS
}

fn is_own_courier(tracker: &StateTracker, unit: &UnitView) -> bool {
    unit.kind == UnitKind::Courier && unit.team == tracker.team && unit.owner == Some(tracker.slot)
}

impl StaticTrackerProvenance {
    pub(crate) fn matches(&self, tracker: &StateTracker) -> bool {
        self.slot == tracker.slot
            && self.team == tracker.team
            && self.metadata == tracker.metadata
            && self.static_trees == tracker.static_trees
            && self.terrain_rle == tracker.terrain_rle
            && self.opaque_cells == tracker.opaque_cells
            && self.shop == tracker.shop
            && self.roster == tracker.roster
    }
}

fn allocate_tracker_lineage() -> Result<NonZeroU64, TrackerError> {
    let lineage = NEXT_TRACKER_LINEAGE
        .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |current| {
            NonZeroU64::new(current).map(|_| current.checked_add(1).unwrap_or(0))
        })
        .map_err(|_| TrackerError::LineageExhausted)?;
    NonZeroU64::new(lineage).ok_or(TrackerError::LineageExhausted)
}

impl TrackerProvenance {
    pub(crate) const fn lineage(&self) -> NonZeroU64 {
        self.lineage
    }

    pub(crate) const fn revision(&self) -> u64 {
        self.revision
    }

    pub(crate) fn matches(&self, tracker: &StateTracker) -> bool {
        self.lineage == tracker.lineage
            && self.revision == tracker.revision
            && self.static_data.matches(tracker)
            && self.previous_snapshot == tracker.previous_snapshot
            && tracker.current.as_ref() == Some(&self.snapshot)
            && self.entities == tracker.entities
            && self.recent_events == tracker.recent_events
            && self.snapshot_events == tracker.snapshot_events
            && self.summaries == tracker.summaries
            && self.last_event_tick == tracker.last_event_tick
            && self.peak_allied_structures == tracker.peak_allied_structures
            && self.peak_enemy_structures == tracker.peak_enemy_structures
            && self.structure_baseline_complete == tracker.structure_baseline_complete
    }

    pub(crate) fn snapshot_precedes(&self, tracker: &StateTracker) -> bool {
        self.lineage == tracker.lineage
            && self.static_data.matches(tracker)
            && tracker.previous_snapshot.as_ref() == Some(&self.snapshot)
    }
}
